apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - rules/podinfo-slo.yaml
  - rules/cost-guardrails.yaml
configMapGenerator:
  - name: dashboard-podinfo-slo
    namespace: monitoring
    files:
      - dashboards/podinfo-slo.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
