#!/usr/bin/env bash
# Day 0, run once from your laptop as subscription Owner:
#   1. apply infra/bootstrap with local state
#   2. migrate that state into the storage account it just created
#   3. write infra/live/lab/backend.hcl and print the GitHub variables
#
# Usage: [TF_BIN=tofu] scripts/bootstrap.sh
set -euo pipefail
source "$(dirname "$0")/lib.sh"

require az jq
require_az_login
TF="$(tf_bin)"
ROOT="$(repo_root)"
BOOT="${ROOT}/infra/bootstrap"

[[ -f "${BOOT}/terraform.tfvars" ]] || die "create ${BOOT}/terraform.tfvars from terraform.tfvars.example first"

# Encryption at host (used by both node pools) is a subscription feature flag.
# Idempotent: a no-op when already registered.
feature_state="$(az feature show --namespace Microsoft.Compute --name EncryptionAtHost --query properties.state -o tsv 2>/dev/null || echo NotRegistered)"
if [[ "${feature_state}" != "Registered" ]]; then
  log INFO "registering Microsoft.Compute/EncryptionAtHost (takes a few minutes)"
  az feature register --namespace Microsoft.Compute --name EncryptionAtHost -o none
  for attempt in $(seq 1 40); do
    feature_state="$(az feature show --namespace Microsoft.Compute --name EncryptionAtHost --query properties.state -o tsv)"
    [[ "${feature_state}" == "Registered" ]] && break
    (( attempt == 40 )) && die "EncryptionAtHost still ${feature_state} after ~10 minutes"
    sleep 15
  done
  az provider register --namespace Microsoft.Compute --wait -o none
fi

cd "${BOOT}"
log INFO "init + apply bootstrap (local state)"
"${TF}" init -input=false
"${TF}" apply -input=false

rg="$("${TF}" output -json backend_config | jq -er '.resource_group_name')"
sa="$("${TF}" output -json backend_config | jq -er '.storage_account_name')"
container="$("${TF}" output -json backend_config | jq -er '.container_name')"

if [[ ! -f backend_override.tf ]]; then
  log INFO "waiting for Storage Blob Data Contributor to propagate (Entra RBAC is eventually consistent)"
  for attempt in $(seq 1 20); do
    if az storage blob list --account-name "${sa}" --container-name "${container}" --auth-mode login --num-results 1 -o none 2>/dev/null; then
      break
    fi
    (( attempt == 20 )) && die "no data-plane access to ${sa} after ~5 minutes"
    sleep 15
  done

  cat > backend_override.tf <<EOF
# Generated by scripts/bootstrap.sh: moves bootstrap state into its own account.
terraform {
  backend "azurerm" {
    resource_group_name  = "${rg}"
    storage_account_name = "${sa}"
    container_name       = "${container}"
    key                  = "bootstrap/bootstrap.tfstate"
    use_azuread_auth     = true
  }
}
EOF
  log INFO "migrating bootstrap state to ${sa}/${container}"
  "${TF}" init -input=false -migrate-state -force-copy
  rm -f terraform.tfstate terraform.tfstate.backup
fi

cat > "${ROOT}/infra/live/lab/backend.hcl" <<EOF
resource_group_name  = "${rg}"
storage_account_name = "${sa}"
container_name       = "${container}"
EOF
log INFO "wrote infra/live/lab/backend.hcl"

vars_json="$("${TF}" output -json github_variables)"
echo
echo "GitHub repository variables (not secrets):"
jq -r 'to_entries[] | "  \(.key)=\(.value)"' <<<"${vars_json}"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  read -r -p "Set them now with gh? [y/N] " answer
  if [[ "${answer}" =~ ^[Yy]$ ]]; then
    jq -r 'to_entries[] | "\(.key)\t\(.value)"' <<<"${vars_json}" | while IFS=$'\t' read -r k v; do
      gh variable set "${k}" --body "${v}"
    done
    log INFO "variables set. Still to do by hand: secret SLACK_WEBHOOK_URL, variable API_ALLOWED_CIDRS, environment 'lab' with required reviewers"
  fi
fi
