# Generated by scripts/bootstrap.sh: moves bootstrap state into its own account.
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-plat-lab-mgmt"
    storage_account_name = "stplattf9byg1"
    container_name       = "tfstate"
    key                  = "bootstrap/bootstrap.tfstate"
    use_azuread_auth     = true
  }
}
